# -*- coding: utf-8 -*-
"""EDC_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1roVHR-A_DeKaqlFG3zIGpEU2h-8t8tc5
"""

!pip install pandas

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

csv_file_path = 'sales_andnoise_byCT.xlsx'
df = pd.read_excel(csv_file_path)

column1 = 'NOISE COUNT'
column2 = 'RESIDENTIAL UNITS TOTAL'

if column1 not in df.columns or column2 not in df.columns:
    raise ValueError(f"Columns '{column1}' or '{column2}' not found in the CSV file.")

data1 = df[column1]
data2 = df[column2]

data = pd.DataFrame({column1: data1, column2: data2})

data = data.replace([float('inf'), -float('inf')], pd.NA).dropna()

cleaned_data1 = data[column1]
cleaned_data2 = data[column2]

correlation_coefficient, p_value = pearsonr(cleaned_data1, cleaned_data2)
print(f"Pearson correlation coefficient: {correlation_coefficient}")
print(f"P-value: {p_value}")

plt.figure(figsize=(12, 6))
sns.regplot(x=cleaned_data1, y=cleaned_data2, scatter_kws={'s':50}, line_kws={'color':'red'})
plt.title(f'Linear Regression of {column1} vs {column2}')
plt.xlabel(column1)
plt.ylabel(column2)
plt.ylim(0, 1000)
plt.grid(True)

plt.show()

correlation_matrix = data.corr()
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', center=0)
plt.title('Correlation Heatmap')
plt.show()

